[package]
name = "advent_of_code_2018"
version = "0.2.0"
authors = ["michael"]
edition = "2018"

[dependencies]
regex = "1"

[profile.release]
#debug = true
lto = true

[features]
run_all = []
